# Generated by Django 4.2.7 on 2023-11-16 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_content', models.TextField(max_length=1000)),
                ('back_content', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_reviewed', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_reviewed', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, choices=[('e', 'Easy'), ('m', 'Medium'), ('h', 'Hard')], default='e', help_text='Progress availability', max_length=1)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='deck.card')),
            ],
            options={
                'ordering': ['next_reviewed'],
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of deck', max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='deck.deck'),
        ),
    ]
