# Generated by Django 4.2.7 on 2023-11-16 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='card',
        ),
        migrations.AddField(
            model_name='progress',
            name='deck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='deck.deck'),
        ),
    ]
